#!/bin/bash
[[ $(screen -list| grep -c 'bot_gen') == '0' ]] && {
    clear
    echo -e "\E[44;1;37m     Kangaroo SSH manager Telegram BOT activation    \E[0m"
    echo ""
    echo -ne "\033[1;32m◇ BOT TOKEN FROM BotFather: "; read token
    echo ""
    echo -ne "\033[1;32m◇ YOUR TELEGRAM ID: "; read idtelegram
    cd /etc/kangaroo_ssh
    screen -dmS bot_gen ./botgerador $token $idtelegram > /dev/null 2>&1
    [[ $(grep -wc "bot_gen" /etc/autostart) = '0' ]] && {
                echo -e "ps x | grep 'bot_gen' | grep -v 'grep' || cd /etc/kangaroo_ssh && sudo screen -dmS bot_gen ./botgerador $token $idtelegram && cd $HOME" >>/etc/autostart
            } || {
                sed -i '/bot_gen/d' /etc/autostart
                echo -e "ps x | grep 'bot_gen' | grep -v 'grep' || cd /etc/kangaroo_ssh && sudo screen -dmS bot_gen ./botgerador $token $idtelegram && cd $HOME" >>/etc/autostart
            }  
    clear && echo "◇ BOT ENABLED!"
} || {
    screen -r -S "bot_gen" -X quit
    clear && echo "◇ BOT DISABLED!"
}
