#!/bin/bash

cor1='\033[41;1;37m'
cor2='\033[44;1;37m'
scor='\033[0m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
SCOLOR='\033[0m'
	ram1=$(free -h | grep -i mem | awk {'print $2'})
	ram2=$(free -h | grep -i mem | awk {'print $4'})
	ram3=$(free -h | grep -i mem | awk {'print $3'})
	uso=$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')
	system=$(cat /etc/issue.net)
	fun_bar() {
		comando[0]="$1"
		comando[1]="$2"
		(
			[[ -e $HOME/fim ]] && rm $HOME/fim
			[[ ! -d /etc/kangaroo_ssh ]] && rm -rf /bin/menu
			${comando[0]} >/dev/null 2>&1
			${comando[1]} >/dev/null 2>&1
			touch $HOME/fim
		) >/dev/null 2>&1 &
		tput civis
		echo -ne "\033[1;33mPLEASE WAIT... \033[1;37m- \033[1;33m["
		while true; do
			for ((i = 0; i < 12; i++)); do
				echo -ne "\033[1;31m#"
				sleep 0.1s
			done
			[[ -e $HOME/fim ]] && rm $HOME/fim && break
			echo -e "\033[1;33m]"
			sleep 1
			tput cuu1
			tput dl1
			echo -ne "\033[1;33mPLEASE WAIT... \033[1;37m- \033[1;33m["
		done
		echo -e "\033[1;33m]\033[1;37m -\033[1;32m DONE!\033[1;37m"
		tput cnorm
	}

	verif_ptrs() {
		porta=$1
		PT=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" | grep -v "COMMAND" | grep "LISTEN")
		for pton in $(echo -e "$PT" | cut -d: -f2 | cut -d' ' -f1 | uniq); do
			svcs=$(echo -e "$PT" | grep -w "$pton" | awk '{print $1}' | uniq)
			[[ "$porta" = "$pton" ]] && {
				echo -e "\n\033[1;31mPORT \033[1;33m$porta \033[1;31mIN USE BY \033[1;37m$svcs\033[0m"
				sleep 1
				fun_conexao
			}
		done
	}
	
  inst_ssl() {
		if netstat -nltp | grep 'stunnel4' 1>/dev/null 2>/dev/null; then
			[[ $(netstat -nltp | grep 'stunnel4' | wc -l) != '0' ]] && sslt=$(netstat -nplt | grep stunnel4 | awk {'print $4'} | awk -F ":" {'print $2'} | xargs) || sslt="\033[1;31mINDISPONIVEL"
			echo -e "\E[44;1;37m              MANAGE  STUNNEL               \E[0m"
			echo -e "\n\033[1;33mPORT:\033[1;37m: \033[1;32m$sslt"
			echo ""
			echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mCHANGE PORT\033[0m"
			echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mUninstall\033[0m"
			echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mMAIN MENU\033[0m"
			echo ""
			echo -ne "\033[1;32mchoose a number from the menu: "
			read menuChoice
			echo ""
			[[ "$menuChoice" = '1' ]] && {
				echo -ne "\033[1;32mEnter Port number: "
				read porta
				echo ""
				[[ -z "$porta" ]] && {
					echo ""
					echo -e "\033[1;31mInvalid port number, try again!"
					sleep 1
					clear
					inst_ssl
				}
				verif_ptrs $porta
				echo -e "\033[1;32mCHANGING STUNNEL Listening PORT ..."
				var2=$(grep 'accept' /etc/stunnel/stunnel.conf | awk '{print $NF}')
				sed -i "s/\b$var2\b/$porta/g" /etc/stunnel/stunnel.conf >/dev/null 2>&1
				echo -e "\033[1;32mRestarting stunnel...\n"
				fun_bar 'service stunnel4 restart' '/etc/init.d/stunnel4 restart'
				echo ""
				netstat -nltp | grep 'stunnel4' >/dev/null && echo -e "\033[1;32msuccesful" || echo -e "\033[1;31mERROR!"
				sleep 2
				clear
				fun_conexao
			}
			[[ "$menuChoicev" = '2' ]] && {
				echo -e "\033[1;32mUn-installing STUNNEL..."
				del_ssl() {
					service stunnel4 stop
					apt-get remove stunnel4 -y
					apt-get autoremove stunnel4 -y
					apt-get purge stunnel4 -y
					rm -rf /etc/stunnel/stunnel.conf
					rm -rf /etc/default/stunnel4
					rm -rf /etc/stunnel/stunnel.pem
				}
				echo ""
				fun_bar 'del_ssl'
				echo ""
				echo -e "\033[1;32mSTUNNEL REMOVED!"
				sleep 1
				fun_conexao
			} || {
				echo -e "\033[1;31mReturning to main menu...\033[0m"
				sleep 1
				fun_conexao
			}
		else
			clear
			echo -e "\E[44;1;37m              INSTALL STUNNEL               \E[0m"
			echo ""
			echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mINSTALL STUNNEL\033[0m"
			echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mmain menu\033[0m"
			echo ""
			echo -ne "\033[1;32mchoose a number from the menu: "
			read menuChoice
			echo ""
            if [[ "$menuChoice" = '1' ]]; then
                echo -ne "\n\033[1;33mForwarding Port(i.e 22): \033[0m"
				read pssl
				portssl="$pssl"
				echo -ne "\n\033[1;33mIncoming port(i.e 443): \033[0m"
        		read porta
				[[ -z "$porta" ]] && {
					echo ""
					echo -e "\033[1;31mInvalid port!"
					sleep 2
					clear
					fun_conexao
				}
            elif [[ "$menuChoice" = '2' ]]; then
				fun_conexao
            else
			echo ""
			echo -e "\033[1;31mInvalid choice\033[0m"
			sleep 1
			inst_ssl
			fi
            clear
				verif_ptrs $porta
				echo -e "\n\033[1;32mINSTALLING STUNNEL...\033[1;33m"
				echo ""
				fun_bar 'apt-get update -y' 'apt-get install stunnel4 -y'
				ssl_conf() {
					echo -e "cert = /etc/stunnel/stunnel.pem\nclient = no\nsocket = a:SO_REUSEADDR=1\nsocket = l:TCP_NODELAY=1\nsocket = r:TCP_NODELAY=1\n\n[stunnel]\nconnect = 127.0.0.1:$portssl\naccept = ${porta}" >/etc/stunnel/stunnel.conf
				}
				ssl_conf
				echo -e "\n\033[1;32mCREATING CERTIFICATE...\033[0m"
				echo ""
				ssl_certif() {
					#crt='EC'
					#openssl genrsa -out key.pem 2048 >/dev/null 2>&1
					#(
					#echo $crt
					#echo $crt
					#echo $crt
					#echo $crt
					#echo $crt
					#echo $crt
					#echo $crt
					#) | openssl req -new -x509 -key key.pem -out cert.pem -days 1050 >/dev/null 2>&1
					#cat cert.pem key.pem >>/etc/stunnel/stunnel.pem
					#rm key.pem cert.pem >/dev/null 2>&1
					sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
					cd /etc/stunnel && wget https://raw.githubusercontent.com/matthew-0x/kangaroo_ssh/main/Sistema/script/stunnel.pem && cd $HOME
				}
				ssl_certif
				echo -e "\n\033[1;32mSTARTING STUNNEL !\033[0m"
				echo ""
				fun_finssl() {
					service stunnel4 restart
					service ssh restart
					/etc/init.d/stunnel4 restart
				}
				fun_bar 'fun_finssl' 'service stunnel4 restart'
				echo -e "\n\033[1;32mStunnel Listening on port: \033[1;33m$porta\033[0m"
				sleep 2
				clear
				fun_conexao
			|| {
				echo -e "\n\033[1;31mReturning...\033[0m"
				sleep 1
				clear
				fun_conexao
			}
		fi
	}

	fun_openssh() {
		clear
		echo -e "\E[44;1;37m            SSH             \E[0m\n"
		echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mCHOOSE PORT\033[1;31m
[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mREMOVE PORT\033[1;31m
[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mReturn to main menu..\033[0m"
		echo ""
		echo -ne "\033[1;32mchoose a number from the menu: "
		read menuChoice
		if [[ "$menuChoice" = '1' ]]; then
			clear
			echo -ne "\033[1;32mWHICH PORT?\033[1;37m "
			read pt
			[[ -z "$pt" ]] && {
				echo -e "\n\033[1;31mInvalid Port!"
				sleep 2
				fun_openssh
			}
			verif_ptrs $pt
			fun_addpssh() {
				echo "Port $pt" >>/etc/ssh/sshd_config
				service ssh restart
			}
			fun_bar 'fun_addpssh'
			echo -e "\n\033[1;32mSSH Port Added.\033[0m"
			sleep 1
			fun_conexao
		elif [[ "$menuChoice" = '2' ]]; then
			clear
			echo -e "\E[41;1;37m         REMOVE SSH PORT         \E[0m"
			echo -e "\n\033[1;33mSSH Current ports: \033[1;37m$(grep 'Port' /etc/ssh/sshd_config | cut -d' ' -f2 | grep -v 'no' | xargs)\n"
			echo -ne "\033[1;32mWhich one to be removed?\033[1;33m?\033[1;37m "
			read pt
			[[ -z "$pt" ]] && {
				echo -e "\n\033[1;31mInvalid Port!"
				sleep 1
				fun_openssh
			}
			[[ $(grep -wc "$pt" '/etc/ssh/sshd_config') ]] && {
				fun_delpssh() {
					sed -i "/Port $pt/d" /etc/ssh/sshd_config
					service ssh restart
				}
				fun_bar 'fun_delpssh'
				echo -e "\n\033[1;32mPORT REMOVED\033[0m"
				sleep 1
				fun_conexao
			} || {
				echo -e "\n\033[1;31mInvalid Port!"
				sleep 1
				fun_openssh
			}
		elif [[ "$menuChoice" = '3' ]]; then
			echo -e "\n\033[1;31mreturning.."
			sleep 2
			fun_conexao
		else
			echo -e "\n\033[1;31mInvalid option!"
			sleep 2
			fun_conexao
		fi
	}

	fun_sslh() {
		[[ "$(netstat -nltp | grep 'sslh' | wc -l)" = '0' ]] && {
			clear
			echo -e "\E[44;1;37m             SSLH INSTALLER               \E[0m\n"
			echo -e "\n\033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mA PORT \033[1;37m443 \033[1;32mWILL BE USED BY STANDARD\033[0m\n"
			echo -ne "\033[1;32mREALLY WANT TO INSTALL SSLH \033[1;31m? \033[1;33m[s/n]:\033[1;37m "
			read menuChoice
			[[ "$menuChoice" = 's' ]] && {
				verif_ptrs 443
				fun_instsslh() {
					[[ -e "/etc/stunnel/stunnel.conf" ]] && ptssl="$(netstat -nplt | grep 'stunnel' | awk {'print $4'} | cut -d: -f2 | xargs)" || ptssl='3128'
					[[ -e "/etc/openvpn/server.conf" ]] && ptvpn="$(netstat -nplt | grep 'openvpn' | awk {'print $4'} | cut -d: -f2 | xargs)" || ptvpn='1194'
					DEBIAN_FRONTEND=noninteractive apt-get -y install sslh
					echo -e "#standalone mode\n\nRUN=yes\n\nDAEMON=/usr/sbin/sslh\n\nDAEMON_OPTS='--user sslh --listen 0.0.0.0:443 --ssh 127.0.0.1:22 --ssl 127.0.0.1:$ptssl --http 127.0.0.1:80 --openvpn 127.0.0.1:$ptvpn --pidfile /var/run/sslh/sslh.pid'" >/etc/default/sslh
					/etc/init.d/sslh start && service sslh start
				}
				echo -e "\n\033[1;32mINSTALLING SSLH !\033[0m\n"
				fun_bar 'fun_instsslh'
				echo -e "\n\033[1;32mSTARTING SSLH !\033[0m\n"
				fun_bar '/etc/init.d/sslh restart && service sslh restart'
				[[ $(netstat -nplt | grep -w 'sslh' | wc -l) != '0' ]] && echo -e "\n\033[1;32mSUCCESSFULLY INSTALLED !\033[0m" || echo -e "\n\033[1;31mUNEXPECTED ERROR !\033[0m"
				sleep 3
				fun_conexao
			} || {
				echo -e "\n\033[1;31mreturning.."
				sleep 2
				fun_conexao
			}
		} || {
			clear
			echo -e "\E[41;1;37m             REMOVE SSLH               \E[0m\n"
			echo -ne "\033[1;32mREALLY WANT TO REMOVE SSLH \033[1;31m? \033[1;33m[s/n]:\033[1;37m "
			read respo
			[[ "$respo" = "s" ]] && {
				fun_delsslh() {
					/etc/init.d/sslh stop && service sslh stop
					apt-get remove sslh -y
					apt-get purge sslh -y
				}
				echo -e "\n\033[1;32mREMOVING SSLH !\033[0m\n"
				fun_bar 'fun_delsslh'
				echo -e "\n\033[1;32mSUCCESSFULLY REMOVED !\033[0m\n"
				sleep 2
				fun_conexao
			} || {
				echo -e "\n\033[1;31mreturning.."
				sleep 2
				fun_conexao
			}
		}
	}

	x="ok"
	fun_conexao() {
		while true $x != "ok"; do
			[[ ! -e '/etc/kangaroo_ssh' ]] && exit 0
			clear
			echo -e "\E[44;1;37m                Configured Services Information                 \E[0m\n"
			echo -e "\033[1;32mSERVICE: \033[1;33mOPENSSH \033[1;32mPORT: \033[1;37m$(grep 'Port' /etc/ssh/sshd_config | cut -d' ' -f2 | grep -v 'no' | xargs)" && sts6="\033[1;32m♦ "

			[[ -e "/etc/stunnel/stunnel.conf" ]] && {
				echo -e "\033[1;32mSERVICE: \033[1;33mSTunnel \033[1;32mPORT: \033[1;37m$(netstat -nplt | grep 'stunnel' | awk {'print $4'} | cut -d: -f2 | xargs)"
				sts3="\033[1;32m♦ "
			} || {
				sts3="\033[1;31m○ "
			}
			
			echo -e "\033[0;34m◇────────────────────────────────────────────────◇\033[0m"
			echo ""
			echo -e "\033[1;31m[\033[1;36m01\033[1;31m] \033[1;37m• \033[1;33mSSH $sts6\033[1;31m
[\033[1;36m02\033[1;31m] \033[1;37m• \033[1;33mSTUNNEL $sts3\033[1;31m
# [\033[1;36m07\033[1;31m] \033[1;37m• \033[1;33mSSLH (MULTIPLEXR) $sts7\033[1;31m
[\033[1;36m03\033[1;31m] \033[1;37m• \033[1;33mReturn to main menu \033[1;32m<\033[1;33m<\033[1;31m< \033[1;31m
[\033[1;36m04\033[1;31m] \033[1;37m• \033[1;33mExit Application \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
			echo ""
			echo -e "\033[0;34m◇────────────────────────────────────────────────◇\033[0m"
			echo ""
			tput civis
			echo -ne "\033[1;32mChoose a menu number: "
			read x
			tput cnorm
			clear
			case $x in
			1 | 01)
				fun_openssh
				;;
			2 | 02)
				inst_ssl
				;;   
			3 | 03)
				menu
				;;
			4 | 04)
				echo -e "\033[1;31mExiting application...\033[0m"
				sleep 1
				clear
				exit
				;;
			*)
				echo -e "\033[1;31mInvalid choice!\033[0m"
				sleep 1
				clear
				fun_conexao
				;;
			esac
		done
	}
	fun_conexao
