#!/bin/bash

IP=$(cat /etc/IP)
cor1='\033[41;1;37m'
cor2='\033[44;1;37m'
scor='\033[0m'
#[[ ! -e /usr/lib/kangaroo_ssh ]] && exit 0
tput setaf 7;tput setab 4;tput bold;printf '%30s%s%-15s\n' "Create SSH User";tput sgr0
echo ""
echo -ne "\033[1;32mUsername:\033[1;37m ";read username
[[ -z $username ]] && {
	echo -e "\n${cor1}Invalid username!${scor}\n"
	exit 1
}
[[ "$(grep -wc $username /etc/passwd)" != '0' ]] && {
	echo -e "\n${cor1}This user already exist!${scor}\n"
	exit 1
}
[[ ${username} != ?(+|-)+([a-zA-Z0-9]) ]] && {
	echo -e "\n${cor1}Invalid username!${scor}"
	echo -e "${cor1}Do not use spaces, accents or special characters!${scor}\n"
	exit 1
}
sizemin=$(echo ${#username})
[[ $sizemin -lt 2 ]] && {
	echo -e "\n${cor1}Username too short(must be between 4-10 characters)${scor}"
	exit 1
}
sizemax=$(echo ${#username})
[[ $sizemax -gt 10 ]] && {
	echo -e "\n${cor1}username too large(must be between 4-10 characters)"
	exit 1
}
echo -ne "\033[1;32mPassword:\033[1;37m ";read password
[[ -z $password ]] && {
	echo -e "\n${cor1}Invalid password!${scor}\n"
	exit 1
}
sizepass=$(echo ${#password})
[[ $sizepass -lt 4 ]] && {
	echo -e "\n${cor1}Short password!, use at least 4 characters${scor}\n"
	exit 1
}
echo -ne "\033[1;32mdays to expire:\033[1;37m ";read dias
[[ -z $dias ]] && {
	echo -e "\n${cor1}Invalid number of days!${scor}\n"
	exit 1
}
[[ ${dias} != ?(+|-)+([0-9]) ]] && {
	echo -e "\n${cor1}Invalid number of days!${scor}\n"
	exit 1
}
[[ $dias -lt 1 ]] && {
	echo -e "\n${cor1}The number must be greater than zero!${scor}\n"
	exit 1
}
echo -ne "\033[1;32mLimit of connections:\033[1;37m ";read sshlimiter
[[ -z $sshlimiter ]] && {
	echo -e "\n${cor1}Invalid limit!${scor}\n"
	exit 1
}
[[ ${sshlimiter} != ?(+|-)+([0-9]) ]] && {
	echo -e "\n${cor1}Invalid limit!${scor}\n"
	exit 1
}
[[ $sshlimiter -lt 1 ]] && {
	echo -e "\n${cor1}limit must be greater than zero!${scor}\n"
	exit 1
}
final=$(date "+%Y-%m-%d" -d "+$dias days")
gui=$(date "+%d/%m/%Y" -d "+$dias days")
pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
useradd -e $final -M -s /bin/false -p $pass $username >/dev/null 2>&1 &
echo "$password" >/etc/kangaroo_ssh/pass/$username
echo "$username $sshlimiter" >> /root/kangaroo_users.db
		
	clear
    echo -e "\033[1;32m===================================="
    echo -e "\033[1;32m   Kangaroo SSH Manager " 
    echo -e "\033[1;32m===================================="
    echo ""
    echo -e "\033[1;37m◈─────⪧ SSH ACCOUNT ⪦─────◈"
    echo ""
    echo -e "\033[1;32m◈ Host / IP   :⪧  \033[1;31m$IP"
    echo -e "\033[1;32m◈ Username    :⪧  \033[1;31m$username"
    echo -e "\033[1;32m◈ Password    :⪧  \033[1;31m$password"
    echo -e "\033[1;32m◈ Login Limit :⪧  \033[1;31m$sshlimiter"
    echo -e "\033[1;32m◈ Expiration  :⪧  \033[1;31m$gui"
    echo ""
    echo -e "\033[1;37m◈─────────────────────────────────◈"

