#!/bin/bash
IP=$(cat /etc/IP)
if [ ! -d /etc/VPSManager/userteste ]; then
mkdir /etc/VPSManager/userteste
fi
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%30s%s%-15s\n' "Create test user" ; tput sgr0
echo ""
[ "$(ls -A /etc/VPSManager/userteste)" ] && echo -e "\033[1;32mActive Test User!\033[1;37m" || echo -e "\033[1;31mNo Active Test Users!\033[0m"
echo ""
for testeson in $(ls /etc/VPSManager/userteste |sort |sed 's/.sh//g')
do
echo "$testeson"
done
echo ""
echo -ne "\033[1;32mEnter Username\033[1;37m: "; read nome
if [[ -z $nome ]]
then
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "invalid name." ; echo "" ; tput sgr0
	exit 1
fi
awk -F : ' { print $1 }' /etc/passwd > /tmp/users 
if grep -Fxq "$nome" /tmp/users
then
	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "This user already exists." ; echo "" ; tput sgr0
	exit 1
fi
echo -ne "\033[1;32mEnter Password\033[1;37m: "; read pass
if [[ -z $pass ]]
then
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "invalid password" ; echo "" ; tput sgr0
	exit 1
fi
echo -ne "\033[1;32mLimit\033[1;37m: "; read limit
if [[ -z $limit ]]
then
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "invalid limit.
" ; echo "" ; tput sgr0
	exit 1
fi
echo -ne "\033[1;32mminutes \033[1;33m(\033[1;31mEx: \033[1;37m60\033[1;33m)\033[1;37m: "; read u_temp
if [[ -z $limit ]]
then
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "invalid limit." ; echo "" ; tput sgr0
	exit 1
fi
useradd -M -s /bin/false $nome
(echo $pass;echo $pass) |passwd $nome > /dev/null 2>&1
echo "$pass" > /etc/kangaroo_ssh/pass/$nome
echo "$nome $limit" >> /root/kangaroo_users.db
echo "#!/bin/bash
pkill -f "$nome"
userdel --force $nome
grep -v ^$nome[[:space:]] /root/kangaroo_users.db > /tmp/ph ; cat /tmp/ph > /root/kangaroo_users.db
rm /etc/VPSManager/senha/$nome > /dev/null 2>&1
rm -rf /etc/VPSManager/userteste/$nome.sh
exit" > /etc/VPSManager/userteste/$nome.sh
chmod +x /etc/VPSManager/userteste/$nome.sh
at -f /etc/VPSManager/userteste/$nome.sh now + $u_temp min > /dev/null 2>&1
clear
    echo -e "\033[1;32m===================================="
    echo -e "\033[1;32m   Kangaroo VPS MANAGER " 
    echo -e "\033[1;32m===================================="
    echo ""
    echo -e "\033[1;37m◈─────⪧ TEST SSH ACCOUNT ⪦─────◈"
    echo ""
    echo -e "\033[1;32m Username   :  \033[1;31m$nome"
    echo -e "\033[1;32m Password   :  \033[1;31m$pass"
    echo -e "\033[1;32m Login Limit:  \033[1;31m$limit"
    echo -e "\033[1;32m Expiration :  \033[1;31m$u_temp minutes"
    echo ""
    echo -e "\033[1;37m◈───⪧ FIND ONLINE USERS USING BELOW LINK⪦────◈ "
    echo ""
    echo -e "\033[1;32mhttp://serverIP:8888/server/online"
    echo ""
    echo -e "\033[1;33mNote: test users will be deleted automatically after the defined time\033[1;32m"
exit
