#!/bin/bash
clear
echo -e "\033[1;32mDo you wish to uninstall this application?[y/n]\033[1;33m"
read resp
if [[ "$resp" = y || "$resp" = Y ]];then
    apt-get purge screen -y > /dev/null 2>&1
    apt-get purge nmap -y > /dev/null 2>&1
    apt-get purge figlet -y > /dev/null 2>&1
    apt-get purge squid -y > /dev/null 2>&1
    apt-get purge squid3 -y > /dev/null 2>&1
    apt-get purge dropbear -y > /dev/null 2>&1
    apt-get purge apache2 -y > /dev/null 2>&1
    rm /root/install /root/version /bin/criarusuario /bin/expcleaner /bin/sshlimiter /bin/addhost /bin/listar /bin/sshmonitor /bin/botmenu /bin/menu /bin/OpenVPN /bin/userbackup /bin/tcpspeed /bin/badvpn /bin/otimizar /bin/speedtest /bin/trafego /bin/banner /bin/limit /bin/limite /bin/change_passwd /bin/restart_module /bin/sys_restart /bin/attscript /bin/criarteste /bin/socks  /bin/DropBear /bin/alterarlimite /bin/alterarsenha /bin/remover /bin/detalhes /bin/mudardata /bin/botssh /bin/infousers /bin/droplimiter /bin/conexao /bin/versao > /dev/null 2>&1
    rm -rf /etc/kangaroo_ssh > /dev/null 2>&1
    clear
    echo -e "\033[1;36mThank you for using Kangaroo ssh manager\033[1;33m"
    sleep 1
else
    echo -e "\033[1;32CTRL+C to exit\033[1;33m"
    sleep 2
    menu
fi
