#!/bin/bash
clear
echo -e "\E[44;1;37m User         Password                Limit           Validity \E[0m"
echo ""
for users in `awk -F : '$3 > 999 { print $1 }' /etc/passwd |sort |grep -v "nobody" | grep -vi "ubuntu" | grep -vi "ec2" |grep -vi "systemd-"`
do
if [[ $(grep -cw $users $HOME/kangaroo_users.db) == "1" ]]; then
    limit=$(grep -w $users $HOME/kangaroo_users.db | cut -d' ' -f2)
else
    limit="1"
fi
if [[ -e "/etc/kangaroo_ssh/pass/$users" ]]; then
    pass=$(cat /etc/kangaroo_ssh/pass/$users)
else
    pass="Null"
fi
expire=$(chage -l $users |grep -i co |awk -F : '{print $2}')
if [ "$expire" == "never" ] 2> /dev/null
then
expdate="\033[1;33mnever\033[0m"
else
    expdate="$(date -d "$expire" +"%Y%m%d")"
    todayDate="$(date -d today +"%Y%m%d")"
    if [ $todayDate -ge $expdate ]
    then
    expText="\033[1;31mExpired\033[0m"
    else
    expdate="$(date -d "$expire" +"%Y-%m-%d")"
    remdays=$(echo -e "$((($(date -ud $expdate +%s)-$(date -ud $(date +%Y-%m-%d) +%s))/86400)) \033[1;37mDays\033[0m")
    fi
fi
Users=$(printf ' %-15s' "$users")
Password=$(printf '%-13s' "$pass")
Limit=$(printf '%-10s' "$limit")
expTxt=$(printf '%-1s' "$expText")
echo -e "\033[1;33m$Users \033[1;37m $Password \033[1;37m $Limit \033[1;32m $expTxt \033[0m"
echo -e "\033[0;34m◇────────────────────────────────────────────────◇\033[0m"
done
echo ""
_tuser=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v ubuntu | grep -v nobody | wc -l)
_ons=$(ps -x | grep sshd | grep -v root | grep -v ec2-user | grep -v ubuntu | grep priv | wc -l)
[[ "$(cat /etc/kangaroo_ssh/Exp)" != "" ]] && _expuser=$(cat /etc/kangaroo_ssh/Exp) || _expuser="0"
#[[ -e /etc/openvpn/openvpn-status.log ]] && _onop=$(grep -c "10.8.0" /etc/openvpn/openvpn-status.log) || _onop="0"
#[[ -e /etc/default/dropbear ]] && _drp=$(ps aux | grep dropbear | grep -v grep | wc -l) _ondrp=$(($_drp - 1)) || _ondrp="0"
#_onli=$(($_ons + $_ondrp))
echo -e "\033[1;33m \033[1;36mTOTAL USERS\033[1;37m $_tuser \033[1;33m \033[1;32mONLINE\033[1;37m: $_ons \033[1;33m \033[1;31mEXPIRED\033[1;37m: $_expuser \033[1;33m\033[0m"