#!/bin/bash
database="/root/kangaroo_users.db"
clear
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "Remove SSH User" ; tput sgr0
echo ""
echo -e "\033[1;31m[\033[1;36m1\033[1;31m]\033[1;33m REMOVE A USER"
echo -e "\033[1;31m[\033[1;36m2\033[1;31m]\033[1;33m REMOVE ALL USERS"
echo -e "\033[1;31m[\033[1;36m3\033[1;31m]\033[1;33m RETURN"
echo ""
read -p "$(echo -e "\033[1;32m◇ Choose a number:\033[1;37m : ")" -e -i 1 resp
if [[ "$resp" = "1" ]]; then
clear
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "Remove SSH User" ; tput sgr0
echo ""
echo -e "\033[1;33m◇ LIST OF USERS: \033[0m"
echo""
_userT=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody)
i=0
unset _userPass
while read _user; do
	i=$(expr $i + 1)
	_oP=$i
	[[ $i == [1-9] ]] && i=0$i && oP+=" 0$i"
	echo -e "\033[1;31m[\033[1;36m$i\033[1;31m] \033[1;37m- \033[1;32m$_user\033[0m"
	_userPass+="\n${_oP}:${_user}"
done <<< "${_userT}"
echo ""
num_user=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
echo -ne "\033[1;32m◇ Enter or select a user \033[1;33m[\033[1;36m1\033[1;31m-\033[1;36m$num_user\033[1;33m]\033[1;37m: " ; read option
user=$(echo -e "${_userPass}" | grep -E "\b$option\b" | cut -d: -f2)
if [[ -z $option ]]; then
	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo " ◇ invalid user!   " ; echo "" ; tput sgr0
	exit 1
elif [[ -z $user ]]; then
	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "◇  invalid user! " ; echo "" ; tput sgr0
	exit 1
else
	if cat /etc/passwd |grep -w $user > /dev/null; then
		echo ""
		pkill -f "$user" > /dev/null 2>&1
		deluser --force $user > /dev/null 2>&1
		echo -e "\E[41;1;37m◇ User $user removed! \E[0m"
		grep -v ^$user[[:space:]] /root/kangaroo_users.db > /tmp/ph ; cat /tmp/ph > /root/kangaroo_users.db
		rm /etc/kangaroo_ssh/users/$user 1>/dev/null 2>/dev/null
		exit 1
	elif [[ "$(cat "$database"| grep -w $user| wc -l)" -ne "0" ]]; then
		ps x | grep $user | grep -v grep | grep -v pt > /tmp/rem
		if [[ `grep -c $user /tmp/rem` -eq 0 ]]; then
			deluser --force $user > /dev/null 2>&1
			echo ""
			echo -e "\E[41;1;37m◇ User $user removed! \E[0m"
			grep -v ^$user[[:space:]] /root/kangaroo_users.db > /tmp/ph ; cat /tmp/ph > /root/kangaroo_users.db
			rm /etc/kangaroo_ssh/users/$user 1>/dev/null 2>/dev/null
			exit 1
		else
		    echo ""
			tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "◇ User is online. Disconnecting..." ; tput sgr0
			pkill -f "$user" > /dev/null 2>&1
			deluser --force $user > /dev/null 2>&1
			echo -e "\E[41;1;37m◇ User $user removed! \E[0m"
			grep -v ^$user[[:space:]] /root/kangaroo_users.db > /tmp/ph ; cat /tmp/ph > /root/kangaroo_users.db
			rm /etc/kangaroo_ssh/users/$user 1>/dev/null 2>/dev/null
			exit 1
		fi
	else
		tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "◇ User $user does not exist!" ; echo "" ; tput sgr0
	fi
fi
elif [[ "$resp" = "2" ]]; then
	clear
	tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "Remove ALL SSH Users" ; tput sgr0
	echo ""
	echo -ne "\033[1;33m◇ REMOVING ALL USERS? \033[1;37m[y/n]: "; read opc	
	if [[ "$opc" = "s" ]]; then
	echo -e "\n\033[1;33m◇ Please Wait...\033[1;32m.\033[1;31m.\033[1;33m.\033[0m"
		for user in $(cat /etc/passwd |awk -F : '$3 > 900 {print $1}' |grep -vi "nobody"); do
			pkill -f $user > /dev/null 2>&1
			deluser --force $user > /dev/null 2>&1
		done
		rm $HOME/kangaroo_users.db && touch $HOME/kangaroo_users.db
        rm *.zip > /dev/null 2>&1
		echo -e "\n\033[1;32m◇SUCCESSFULLY REMOVED ALL USERS!\033[0m"
		sleep 2
		menu
	else
		echo -e "\n\033[1;31m◇ Returning to the main menu...\033[0m"
		sleep 2
		menu
	fi
elif [[ "$resp" = "3" ]]; then
	menu
else
	echo -e "\n\033[1;31m◇ Invalid option!\033[0m"
	sleep 1.5s
	menu
fi
