#!/bin/bash
clear
wait_bar () {
command[0]="$1"
command[1]="$2"
 (
[[ -e $HOME/kvpn ]] && rm $HOME/kvpn
${command[0]} > /dev/null 2>&1
${command[1]} > /dev/null 2>&1
touch $HOME/kvpn
 ) > /dev/null 2>&1 &
tput civis
echo -ne "   \033[1;33mPLEASE WAIT ... \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/kvpn ]] && rm $HOME/kvpn && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "   \033[1;33mPLEASE WAIT ... \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m Done!\033[1;37m"
tput cnorm
}
echo " "
versionChecker () {
  [[ -e /home/version ]] && rm /home/version
  [[ -e /tmp/att ]] && rm /tmp/att
	wget -c -P /home https://raw.githubusercontent.com/matthew-0x/kangaroo_ssh/main/Sistema/version
	[[ -f "/home/version" ]] && mv /home/version /tmp/att
	[[ ! -e /bin/version ]] && rm -rf /bin/menu
} > /dev/null 2>&1
echo -e "### Kangaroo SSH Manager ###" | figlet
echo " "
echo -e "   \033[1;32m◇ CHECKING FOR AVAILABLE UPDATES\033[0m\n"
wait_bar 'versionChecker'
[[ ! -f "/tmp/att" ]] && {
	echo -e "\n\033[1;31m◇ ERROR CONNECTING TO SERVER\n"
	echo -ne "\033[1;31m◇ Return to main menu(press enter)\033[0m"; read
	menu
}

echo " "
vrs1=$(sed -n '1 p' /bin/version| sed -e 's/[^0-9]//ig')
vrs2=$(sed -n '1 p' /tmp/att | sed -e 's/[^0-9]//ig')
[[ "$vrs1" == "$vrs2" ]] && {
  echo -e " \033[1;36m  ◇ You have the latest version!\033[0m\n"
  rm /tmp/att > /dev/null 2>&1
  echo -ne "\033[1;31m◇ Return to main menu(press enter)\033[0m"; read
  menu
} || {
  echo -e "  \033[1;36m◇ THERE IS A NEW UPDATE AVAILABLE!\033[1;33m\n"
  echo -e "  \033[1;32m◇ New Version:\033[0m\n"
  while read verInfo; do
    echo -e "  \033[1;37m- \033[1;33m$verInfo"
  done < "/tmp/att"
  echo " "
  echo -ne "  \033[1;32m◇ Do you wish to UPDATE? \033[1;33m[y/n]:\033[1;37m "; read res
  if [[ "$res" = y || "$res" = Y ]];then
    echo -e "\n\033[1;32m◇ STARTING THE UPDATE..."
    sleep 2
    wget https://raw.githubusercontent.com/matthew-0x/kangaroo_ssh/main/installation_script > /dev/null 2>&1
    chmod +x installation_script
    ./installation_script
    clear
    echo -e "\033[1;32m◇ SCRIPT UPDATED SUCCESSFULLY \033[0m\n"
    rm /tmp/att > /dev/null 2>&1
    echo -ne "\033[1;31m◇ Return to main menu(press enter)\033[0m"; read
    menu
  else
    menu
  fi
}

