#!/bin/bash
clear
[[ -e /home/uversion ]] && rm /home/uversion
wget -P /home https://raw.githubusercontent.com/matthew-0x/kangaroo_ssh/main/dependencies/uversion > /dev/null 2>&1
[[ -f "/home/version" ]] && {
	vrs1=$(sed -n '1 p' /bin/version| sed -e 's/[^0-9]//ig')
    vrs2=$(sed -n '1 p' /home/uversion | sed -e 's/[^0-9]//ig')
	[[ "$vrs1" != "$vrs2" ]] && mv /home/uversion /tmp/att
}
