#!/bin/bash
clear
[[ "$(whoami)" != "root" ]] && {
echo -e "\033[1;33m◇ YOU NEED TO RUN AS ROOT!\033[0m"
exit 0
}
_lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r'| sed -e 's/[^a-z.]//ig'| rev)
_Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig')
_1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
cd $HOME
wait_bar () {
comando[0]="$1"
comando[1]="$2"
(
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
) > /dev/null 2>&1 &
tput civis
echo -ne "  \033[1;33m◇ PLEASE WAIT... \033[1;37m- \033[1;33m["
while true; do
for((i=0; i<18; i++)); do
echo -ne "\033[1;31m#"
sleep 0.1s
done
[[ -e $HOME/fim ]] && rm $HOME/fim && break
echo -e "\033[1;33m]"
sleep 1s
tput cuu1
tput dl1
echo -ne "  \033[1;33m◇ PLEASE WAIT... \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37mDONE!\033[1;37m"
tput cnorm
}
function verif_key () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev)
chmod +x $_Ink/list > /dev/null 2>&1
[[ ! -e "$_Ink/list" ]] && {
echo -e "\n\033[1;31m◇ KEY INVALID!\033[0m"
sleep 1
clear; exit 1
}
}
echo -e "\033[1;31m\033[0m"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "Welcome to Kangaroo SSH Manager" ; tput sgr0
echo ""
#-----------------------------------------------------------------------------------------------------------------
echo -ne "\033[1;36m◇ Proceed with installation? [Y/N]: \033[1;37m"; read x
[[ $x = @(n|N) ]] && exit
rm $_Ink/list > /dev/null 2>&1
wget -P $_Ink https://raw.githubusercontent.com/matthew-0x/kangaroo_ssh/main/dependencies/list > /dev/null 2>&1
echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
cd /bin
#rm version* > /dev/null 2>&1
#wget https://raw.githubusercontent.com/matthew-0x/kangaroo_ssh/main/dependencies/version > /dev/null 2>&1

#-----------------------------------------------------------------------------------------------------------------
#optiondb=2
[[ -f "$HOME/kangaroo_users.db" ]] && {
clear
echo -e "\n\033[0;34m◇───────────────────────────────────────────────────◇\033[0m"
echo ""
echo -e "\033[1;33mA User Database For This Program Already Exist "
echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mUse Existing Database\033[0m"
echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCreate a New Database\033[0m"
echo -e "\n\033[0;34m◇───────────────────────────────────────────────────◇\033[0m"
echo ""
tput setaf 2  
tput bold 
read -p "Choose a number from above (default value 2): " optiondb 
tput sgr0
}
if [[ "$optiondb" == "2" ]]; then
    awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > "$HOME/kangaroo_users.db"
fi
add_date () {
[[ ! -d /usr/share/.date ]] && mkdir /usr/share/.date
echo "crz: $(date)" > /usr/share/.date/.install_time
}
add_date
install_pkg () {
_packages=("bc" "screen" "unzip" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "python3" "python-pip")
for _prog in ${_packages[@]}; do
apt install $_prog -y
done
#pip install speedtest-cli
}
wait_bar 'install_pkg'
#wait_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
echo ""
cd $HOME
