#!/bin/bash

_version=$(wget -qO- https://raw.githubusercontent.com/matthew-0x/kangaroo_ssh/main/Sistema/version)
ip=$(wget -qO- ipecho.net/plain)
echo -e "$ip" >/etc/IP
lst1=$1
echo -e "Australia/Sydney" >/etc/timezone
ln -fs /usr/share/zoneinfo/Australia/Sydney /etc/localtime >/dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata >/dev/null 2>&1
[[ -z $lst1 ]] && {
	rm -rf $_Ink/list >/dev/null 2>&1 && exit 0
}
[[ ! -d /etc/kangaroo_ssh ]] && mkdir /etc/kangaroo_ssh
[[ ! -d /etc/kangaroo_ssh/pass ]] && mkdir /etc/kangaroo_ssh/pass
[[ ! -e /etc/kangaroo_ssh/Exp ]] && touch /etc/kangaroo_ssh/Exp
[[ ! -d /etc/kangaroo_ssh/testuser ]] && mkdir /etc/kangaroo_ssh/testuser
[[ ! -d /etc/kangaroo_ssh/.tmp ]] && mkdir /etc/kangaroo_ssh/.tmp
#[[ ! -d /etc/kangaroo_bot ]] && mkdir /etc/kangaroo_bot
#[[ ! -d /etc/kangaroo_bot/info-users ]] && mkdir /etc/kangaroo_bot/info-users
#[[ ! -d /etc/kangaroo_bot/arquivos ]] && mkdir /etc/kangaroo_bot/arquivos
#[[ ! -d /etc/kangaroo_bot/revenda ]] && mkdir /etc/kangaroo_bot/revenda
#[[ ! -d /etc/kangaroo_bot/suspensos ]] && mkdir /etc/kangaroo_bot/suspensos
#[[ ! -e /etc/kangaroo_bot/lista_ativos ]] && touch /etc/kangaroo_bot/lista_ativos
#[[ ! -e /etc/kangaroo_bot/lista_suspensos ]] && touch /etc/kangaroo_bot/lista_suspensos
#echo -e 'by: @kangaroo_ssh' >/usr/lib/kangaroo_ssh && cat /usr/lib/kangaroo_ssh >$lst2/licence && cat /usr/lib/kangaroo_ssh > /etc/kangaroo_ssh/.tmp/vps
#netstat -nplt | grep -w 'apache2' | grep -w '80' && sed -i "s/Listen 80/Listen 8888/g" /etc/apache2/ports.conf && service apache2 restart
#[[ "$(grep -o '#Port 22' /etc/ssh/sshd_config)" == "#Port 22" ]] && sed -i "s;#Port 22;Port 22;" /etc/ssh/sshd_config && service ssh restart
grep -v "^PasswordAuthentication" /etc/ssh/sshd_config >/tmp/passlogin && mv /tmp/passlogin /etc/ssh/sshd_config
echo "PasswordAuthentication yes" >>/etc/ssh/sshd_config
_bin='/bin'
_etc='/etc/kangaroo_ssh'
_root='/root'
#rm $_etc/ShellBot.sh $_etc/cabecalho >/dev/null 2>&1
_mdls=("menu" "bot" "test_bot_ssh" "changepass" "criarusuario" "expcleaner" "mudardata" "remover" "criarteste" "verifbot" "droplimiter" "userlimits" "botmenu" "sshmonitor" "badvpn" "userbackup" "instsqd" "blockt" "optimiser" "speedtest" "banner" "restart_module" "sys_restart" "updatescript" "conexao" "delscript" "detalhes" "botssh"  "test_bot" "botgen" "infousers" "versioncheck" "limiter" "uexpired" "cabecalho")
#_mdls2=("onlineapp.sh")
for _arg in ${_mdls[@]}; do
	[[ -e $_bin/$_arg ]] && rm $_bin/$_arg >/dev/null 2>&1
	if wget -c -P $_bin https://raw.githubusercontent.com/matthew-0x/kangaroo_ssh/main/modules/$_arg; then
      chmod +x $_bin/$_arg
  else
      echo "Error: $_arg does not exist online or could not be downloaded."
  fi
done
#for _arq in ${_mdls2[@]}; do
#	[[ -e $_dir3/$_arq ]] && rm $_dir3/$_arq >/dev/null 2>&1
#	wget -c -P $_dir3 https://raw.githubusercontent.com/matthew-0x/kangaroo_ssh/main/modules/$_arq
#	chmod +x $_dir3/$_arq
#done
#cd /var/www/html && mkdir server
#cd /root && ./onlineapp.sh
#mv $_bin/cabecalho $_bin/bot $_bin/test_bot_ssh $_bin/botgerador $_etc

#[[ ! -e /etc/autostart ]] && {
#	echo #!/bin/bash
#clear
#AUTOMATIC START' >/etc/autostart
#chmod +x /etc/autostart 
#} || {
#	[[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) != '0' ]] && wget -qO- https://raw.githubusercontent.com/matthew-0x/kangaroo_ssh/main/dependencies/ShellBot.sh
#	for proc in $(ps x | grep 'dmS' | grep -v 'grep' | awk {'print $1'}); do
#		screen -r -S "$proc" -X quit	
#done
#	screen -wipe >/dev/null
#	echo '#!/bin/bash
#clear

#AUTOMATIC START' >/etc/autostart
#	chmod +x /etc/autostart
#} || {
#	[[ $(ps x | grep "test_bot" | grep -v grep | wc -l) != '0' ]] && wget -qO- https://raw.githubusercontent.com/matthew-0x/kangaroo_ssh/main/Install/ShellBot.sh
#	for proc in $(ps x | grep 'dmS' | grep -v 'grep' | awk {'print $1'}); do
#		screen -r -S "$proc" -X quit	
#done
#	screen -wipe >/dev/null
#	echo '#!/bin/bash
#clear

#AUTOMATIC START' >/etc/autostart
#	chmod +x /etc/autostart
#} || {
#	[[ $(ps x | grep "bot_gen" | grep -v grep | wc -l) != '0' ]] && wget -qO- https://raw.githubusercontent.com/matthew-0x/kangaroo_ssh/main/Install/ShellBot.sh
#	for proc in $(ps x | grep 'dmS' | grep -v 'grep' | awk {'print $1'}); do
#		screen -r -S "$proc" -X quit	
#done
#	screen -wipe >/dev/null
#	echo '#!/bin/bash
#clear

#AUTOMATIC START' >/etc/autostart
#	chmod +x /etc/autostart
#} 
#comment >>
#crontab -r >/dev/null 2>&1
(
	#echo "@reboot /etc/autostart"
	#echo "* * * * * /etc/autostart"
	echo "0 */6 * * * /bin/uexpired"
	#echo "*/1 * * * * cd /root/ && ./onlineusers.sh"
) | crontab -
echo "$_version" | sed -n '1 p' | cut -d' ' -f2 >/bin/version && cat /bin/version >/root/version
#wget https://raw.githubusercontent.com/matthew-0x/kangaroo_ssh/main/Install/jq-linux64 >/dev/null 2>&1
#chmod +x jq-linux64 && mv jq-linux64 $(which jq)
service cron restart >/dev/null 2>&1
service ssh restart >/dev/null 2>&1
#[[ -d /var/www/html/openvpn ]] && service apache2 restart >/dev/null 2>&1
rm -rf $lst1/list >/dev/null 2>&1
